### ISSUE TITLE
Expo SDK35 Error

### ISSUE THREAD

**Issue by kanapan** [hyakt/expo-multiple-media-imagepicker#3]
I can't use in expo SDK 35

**Comment by zlanich** [comment]
I may also be experiencing this issue. My error was "Cannot redefine property CodedError".

**Comment by Aryk** [comment]
Does it work in the SDK 37?

**Comment by sunviwo** [comment]
Having the same error as @zlanich, expo SDK 38

**Comment by gioramies** [comment]
> Does it work in the SDK 37?

@Aryk Did it worked for you?

**Comment by SirPhemmiey** [comment]
Hi guys, did this work on expo sdk 38?

**Comment by gioramies** [comment]
This https://github.com/MonstroDev/expo-image-picker-multiple worked for me with SDK 39

**Comment by SirPhemmiey** [comment]
Nice, will check it though i'm still using sdk 38. Thanks so much
